/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.livrojogo;
import java.util.Random;
import javax.swing.ImageIcon;



/**
 *
 * @author Vitor
 */
public class JFrame1 extends javax.swing.JFrame {

    /**
     * Creates new form JFrame1
     */
    public JFrame1() {
        initComponents();
        
    }
    
    public void Foto()
    {
        ImageIcon imagem = new ImageIcon(getClass().getResource("/noite_rua.png"));
        jLabel1.setIcon(imagem);
        
    }
    public void Foto1()
    {
        ImageIcon imagem1 = new ImageIcon(getClass().getResource("/bandidos.png"));
        jLabel1.setIcon(imagem1);
        
    }
    public void Foto2()
    {
        ImageIcon imagem = new ImageIcon(getClass().getResource("/bandidos1.png"));
        jLabel1.setIcon(imagem);
        
    }
    public void Foto3()
    {
        ImageIcon imagem = new ImageIcon(getClass().getResource("/bandidos2.png"));
        jLabel1.setIcon(imagem);
        
    }
    public void Foto4()
    {
        ImageIcon imagem = new ImageIcon(getClass().getResource("/bandidos3.png"));
        jLabel1.setIcon(imagem);
        
    }
    public void Foto5()
    {
        ImageIcon imagem = new ImageIcon(getClass().getResource("/taverna.png"));
        jLabel1.setIcon(imagem);
        
    }
    public void Foto6()
    {
        ImageIcon imagem = new ImageIcon(getClass().getResource("/estrada.png"));
        jLabel1.setIcon(imagem);
        
    }
    public void Foto7()
    {
        ImageIcon imagem = new ImageIcon(getClass().getResource("/caverna.png"));
        jLabel1.setIcon(imagem);
        
    }
    public void Foto8()
    {
        ImageIcon imagem = new ImageIcon(getClass().getResource("/ovo.png"));
        jLabel1.setIcon(imagem);
        
    }
    public void Foto9()
    {
        ImageIcon imagem = new ImageIcon(getClass().getResource("/combat.png"));
        jLabel1.setIcon(imagem);
        
    }
    public void Foto10()
    {
        ImageIcon imagem = new ImageIcon(getClass().getResource("/eco.png"));
        jLabel1.setIcon(imagem);
        
    }
    public void Foto11()
    {
        ImageIcon imagem = new ImageIcon(getClass().getResource("/combat.png"));
        jLabel1.setIcon(imagem);
        
    }
    public void Foto12()
    {
        ImageIcon imagem = new ImageIcon(getClass().getResource("/dragaomorto.png"));
        jLabel1.setIcon(imagem);
        
    }
    public void Foto13()
    {
        ImageIcon imagem = new ImageIcon(getClass().getResource("/cidade.png"));
        jLabel1.setIcon(imagem);
        
    }
    public void Foto14()
    {
        ImageIcon imagem = new ImageIcon(getClass().getResource("/destroi.png"));
        jLabel1.setIcon(imagem);
        
    }
    public void Foto15()
    {
        ImageIcon imagem = new ImageIcon(getClass().getResource("/correr.png"));
        jLabel1.setIcon(imagem);
        
    }
    public void Foto16()
    {
        ImageIcon imagem = new ImageIcon(getClass().getResource("/cavalgar.png"));
        jLabel1.setIcon(imagem);
        
    }
    
    public void Morte()
    {
        ImageIcon imagem = new ImageIcon(getClass().getResource("/morte.png"));
        jLabel1.setIcon(imagem);
        jTextArea1.setText("    \n" +
        "          Você não suportou os ferimentos, você está morto!\n");
        jTextField1.setText("     Aperte \"Aceitar\"para continuar");
        num = 100;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        BtnAceitar1 = new javax.swing.JButton();
        BtnRecusar1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        BntDestreza = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        Usar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vitor\\Documents\\NetBeansProjects\\Livro Jogo\\LivroJogo\\src\\main\\resources\\taverna1.jpg")); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(153, 153, 153)));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Sitka Heading", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("    \n          Numa noite sombria, voce encontra-se na Taverna\n     do Trovão,  um  local  escuro  e acolhedor onde lendas \n     começam.   Enquanto  voce  saboreia  sua  bebida,  um \n     estranho  mapa  é  entregue  a voce por um forasteiro. \n     O  mapa  indica  a localização  de  uma antiga caverna \n     onde supostamente repousa um tesouro incrível.");
        jTextArea1.setAlignmentX(10.0F);
        jTextArea1.setAlignmentY(10.0F);
        jTextArea1.setAutoscrolls(false);
        jTextArea1.setBorder(null);
        jTextArea1.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextArea1.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jTextArea1.setFocusable(false);
        jScrollPane1.setViewportView(jTextArea1);

        BtnAceitar1.setBackground(new java.awt.Color(153, 204, 255));
        BtnAceitar1.setText("Aceitar");
        BtnAceitar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAceitar1ActionPerformed(evt);
            }
        });

        BtnRecusar1.setBackground(new java.awt.Color(153, 204, 255));
        BtnRecusar1.setText("Recusar");
        BtnRecusar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRecusar1ActionPerformed(evt);
            }
        });

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Sitka Heading", 0, 14)); // NOI18N
        jTextField1.setText("     Deseja aceitar o mapa e os conselhos do forasteiro?");
        jTextField1.setFocusable(false);

        BntDestreza.setBackground(new java.awt.Color(153, 204, 255));
        BntDestreza.setText("Destreza");
        BntDestreza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BntDestrezaActionPerformed(evt);
            }
        });

        jTextField2.setEditable(false);
        jTextField2.setText("0");

        jLabel2.setText("Vida:");

        jLabel3.setText("Poção de vida:");

        jLabel4.setText("Moedas:");

        jTextField3.setText("100");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jTextField4.setText("2");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jTextField5.setText("80");
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        Usar.setBackground(new java.awt.Color(153, 204, 255));
        Usar.setText("Usar");
        Usar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
            .addComponent(jTextField1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnAceitar1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(BntDestreza))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Usar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnRecusar1)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAceitar1)
                    .addComponent(BtnRecusar1)
                    .addComponent(BntDestreza)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Usar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int num = 1;
    int destreza = 0;
    int aleatorio;
    int vida = 100;
    int pocao = 2;
    int moeda = 80;
    int ataque = 10;
    int inimigo = 3;
    
    private void BtnAceitar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAceitar1ActionPerformed
        jTextField2.setText(String.valueOf(destreza));
        
        if (num == 100 && destreza == 0)
        {
            Intro intro = new Intro();
            intro.setLocationRelativeTo(null);
            intro.setVisible(true);   
            dispose();
        }
        
        if (num == 1 && destreza == 0)
        {
            Foto();
            jTextArea1.setText("    \n" +
            "          Voce observa atentamente as instruções do mapa,\n" +
            "     toma seu último gole e segue em direção a porta da \n" +
            "     taverna. Na rua a neblina engole toda a paisagem além\n" +  
            "     de dez metros à sua frente. Você desamarra seu cavalo\n" +                    
            "     e então segue em direção à caverna. Já fora da cidade \n" +
            "     você escuta uma voz feminina pedindo socorro.\n");
            jTextField1.setText("     Você vai seguir o chamado de ajuda?");
        }
        if (num == 2 && destreza == 0)
        {
            Foto1();
            jTextArea1.setText("    \n" +
            "          Você chega onde aparentemente alguém precisa de\n" +
            "     ajuda,  mas  a  voz que você  seguiu era de uma ladra\n" +
            "     que, junto de seus 2  comparsas, enganam cidadãos e os\n" +  
            "     conduzem pra fora da estrada com a intenção de roubar \n" +                    
            "     e matar! Eles rapidamente sacam suas armas e partem\n" +
            "     em sua direção.\n");
            jTextField1.setText("     Teste sua destreza, você deve tirar mais que 4.");
            destreza = 1;
            
        }
        if (num == 3 && destreza == 0)
        {
            Foto7();
            jTextArea1.setText("    \n" +
            "          Você segue rigorosamente os passos e indicações do\n" +
            "     mapa e encontra a caverna, ao chegar na entrada da mesma\n" +
            "     você escuta, vindo de dentro da caverna, um rosnar grave\n" +  
            "     que ecoa fazendo tripidar as pequenas pedras ao seu redor\n" +                    
            "     \n" +
            "     Você se assusta e perde o equilíbrio!\n");
            jTextField1.setText("     Teste sua destreza, você deve tirar mais que 4.");
            destreza = 2;
            
        }
        if (num == 4 && destreza == 0)
        {
            Foto8();
            jTextArea1.setText("    \n" +
            "          Ao chegar às profundezas da caverna, você descobre\n" +
            "     o verdadeiro tesouro: um ovo de dragão vermelho!\n" +
            "     Este artefato é extremamente raro, conferindo-lhe um valor\n" +  
            "     incalculável. A sua comercialização junto aos conhecedores\n" +                    
            "     certos tem o potencial não apenas de enriquecer,mas de \n" +
            "     tornar qualquer indivíduo verdadeiramente próspero.\n");
            jTextField1.setText("     Aperte \"Aceitar\"para continuar");
        }
        
        if (num == 5 && destreza == 0)
        {
            Foto9();
            jTextArea1.setText("    \n" +
            "          Antes que você possa decidir o que fazer,as chamas\n" +
            "     da caverna acendem-se, revelando a presença de um temível\n" +
            "     dragão vermelho, a guardiã do ovo.\n"+
            "     Você agora enfrenta um dilema: fugir com o ovo ou matar\n"+
            "     o dragão.\n");
            jTextField1.setText("     Enfrentar o dragão(Aceitar), fugir(Recusar).");
        }
        if (num == 6 && destreza == 0)
        {
            Foto9();
            jTextArea1.setText("    \n" +
            "          Antes que você possa decidir o que fazer,as chamas\n" +
            "     da caverna acendem-se, revelando a presença de um temível\n" +
            "     dragão vermelho.\n"+
            "     É hora de lutar por sua vida!\n");
            jTextField1.setText("     Teste sua destreza, você deve tirar mais que 4.");
            destreza = 3;
            ataque = 20;
            inimigo = 10;
        }
        
        if (num == 8 && destreza == 0)
        {
            Foto8();
            jTextArea1.setText("    \n" +
            "          Após vencer o temível dragão, mesmo exausto e ferido,\n" +
            "     você avança em direção ao verdadeiro tesouro: o ovo de dragão\n" +
            "     vermelho. Sua conquista se traduz em riquezas\n");
            jTextField1.setText("     Aperte \"Aceitar\"para continuar");
            
        }
        
        if (num == 9 && destreza == 0)
        {
            Foto13();
            jTextArea1.setText("    \n" +
            "          Ao adentrar a cidade, ostentando o tão sonhado ovo,\n" +
            "     todos os  cidadãos  reverenciam o  verdadeiro  herói da \n" +
            "     cidade. Agora, você se transforma em uma lenda que ecoará\n"+
            "     através de muitas gerações.\n"+
            "     \n"+
            "     Este é o fim da aventura!\n");
            jTextField1.setText("     Aperte \"Aceitar\"para continuar");
            num =99;
        }
        
        if (num == 10 && destreza == 0)
        {
            Foto14();
            jTextArea1.setText("    \n" +
            "          Mas o que ninguém imaginava é que o dragão conseguiria\n" +
            "     farejar sua cria e fora atraído diretamente para a cidade.\n" +
            "     Agora o dragão enfurecido destrói e mata tudo a sua frente\n"+
            "     não restando mais ninguém vivo!\n"+
            "     \n"+
            "     Este é o fim da aventura!\n");
            jTextField1.setText("     Aperte \"Aceitar\"para continuar");
            num = 99;
            
        }
        num = num+1;
        
        
    }//GEN-LAST:event_BtnAceitar1ActionPerformed
        
    private void BntDestrezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BntDestrezaActionPerformed
        
        Random random = new Random();
        jTextField3.setText(String.valueOf(vida));
        jTextField4.setText(String.valueOf(pocao));
        jTextField5.setText(String.valueOf(moeda));
     
        if(destreza == 1)
        {
            
                aleatorio = random.nextInt(10)+1;
                jTextField2.setText(String.valueOf(aleatorio));
                
                if(aleatorio>0 && aleatorio <5)
                {
                    vida = vida-ataque;
                    jTextField1.setText("     Você recebeu " +ataque+ " de dano, tente novamente. ");
                    jTextField3.setText(String.valueOf(vida));
                    aleatorio = 0;
                        if(vida<1)
                        {
                            Morte();
                            destreza = 0;
                        }
                }else
                {
                    inimigo = inimigo-1;
                    
                    
                    switch(inimigo)
                    {
                        case 2:
                            Foto2();
                            jTextField1.setText("     Você matou 1 bandido, resta(m) "+inimigo+", use sua Destreza.");
                            aleatorio = 0;
                        break;
                        
                        case 1:
                            Foto3();
                            jTextField1.setText("     Você matou 1 bandido, resta(m) "+inimigo+", use sua Destreza.");
                            aleatorio = 0;
                        break;
                        
                        case 0:
                            Foto4();
                            aleatorio = random.nextInt(10)+1;
                            moeda = moeda + aleatorio;
                            jTextField5.setText(String.valueOf(moeda));
                            jTextArea1.setText("    \n" +
                            "          Você matou os três bandidos e ao vasculhar seus \n" +
                            "     corpos encontrou "+aleatorio+" moeda(s), você as guarda em seu\n" +
                            "     bolso, pega seu cavalo e retorna para a estrada.\n");
                            jTextField1.setText("     Aperte \"Aceitar\"para continuar");
                            destreza = 0;
                            num = 3;
                            break;
                    }
                } 
                
                
            
        } 
        if(destreza == 2)
        {
            aleatorio = random.nextInt(10)+1;
            jTextField2.setText(String.valueOf(aleatorio));
            
            if(aleatorio >4)
            {
                jTextArea1.setText("    \n" +
                "          Apesar do susto, você consegue se manter em pé e não\n" +
                "     faz nenhum barulho que pudesse entregar sua presença e ser\n" +
                "     notado pela criatura em seu covio\n" +  
                "     Lentamente você se esgueira para dentro da caverna\n");
                jTextField1.setText("     Aperte \"Aceitar\"para continuar");
                num = 4;
                destreza = 0;
            }else
            {
                Foto10();
                jTextArea1.setText("    \n" +
                "          Ao cambalear no interior da caverna, seus pertences\n" +
                "     colidem abruptamente com as rochas, gerando um estrondo\n" +
                "     ensurdecedor ecoando escuridão a dentro.\n");
                jTextField1.setText("     Aperte \"Aceitar\"para continuar");
                num = 6;
                destreza = 0;
            }
        }
        if(destreza == 3)
        {    
            if (inimigo > 0)
            {
                aleatorio = random.nextInt(10)+1;
                jTextField2.setText(String.valueOf(aleatorio));
                
                while(aleatorio>0 && aleatorio <5)
                {
                    vida = vida-ataque;
                    jTextField1.setText("     Você recebeu " +ataque+ " de dano, tente novamente. ");
                    jTextField3.setText(String.valueOf(vida));
                    aleatorio = 0;
                        if(vida<1)
                        {
                            Morte();
                            destreza = 0;
                        }
                }
                
                while(aleatorio>4)
                {
                    inimigo = inimigo-1;
                    
                    jTextField1.setText("     Você feriu o dragão, ele tem mais "+inimigo+" de vida, use sua Destreza.");
                    aleatorio = 0;
                    
                    if(inimigo == 0)
                    {
                        Foto12();
                        aleatorio = random.nextInt(10)+1;
                        moeda = moeda + aleatorio;
                        jTextField5.setText(String.valueOf(moeda));
                        jTextArea1.setText("    \n" +
                        "          Você esquiva como o vento, se movimenta como a água e \n" +
                        "     cada investida é precisa e certeira, ao final o gigante\n" +
                        "     dragão cuspidor de fogo não resiste e tomba à sua frente\n" +
                        "     o imponente dragão está morto!");
                        jTextField1.setText("     Aperte \"Aceitar\"para continuar");
                        destreza = 0;
                        num = 8;
                    }
                }    
            }
        }
        if(destreza == 4)
        {    
            
                aleatorio = random.nextInt(10)+1;
                jTextField2.setText(String.valueOf(aleatorio));
                
                if(aleatorio>0 && aleatorio <5)
                {
                    vida = vida-ataque;
                    jTextField1.setText("     Você recebeu " +ataque+ " de dano, tente novamente. ");
                    jTextField3.setText(String.valueOf(vida));
                    aleatorio = 0;
                        if(vida<1)
                        {
                            Morte();
                            destreza = 0;
                        }
                }else
                {
                    inimigo = inimigo - 1;
                    if(inimigo >0)
                    {
                        jTextField1.setText("     Você esquivou da baforada, resta(m) "+inimigo+", use sua Destreza.");
                        aleatorio = 0;
                    }else
                    {
                        Foto16();
                        jTextArea1.setText("    \n" +
                        "          Você pulou, rolou, esquivou e conseguiu alcançar a \n" +
                        "     entrada da caverna, rapidamente você montou em seu cavalo\n" +
                        "     que cavalgou  como o  vento entre as árvores da floresta.\n"+
                        "     Ufa! Você conseguiu despistar o dragão!\n"+
                        "     Chegando  na  cidade, você  exibe seu troféu, os cidadãos\n"+
                        "     que te reverenciam como um grande herói!\n");
                        jTextField1.setText("     Aperte \"Aceitar\"para continuar");
                        num = 10;
                        destreza = 0;
                    }
                }
                
                    
            
        }
        
    }//GEN-LAST:event_BntDestrezaActionPerformed
    
    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void BtnRecusar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRecusar1ActionPerformed
        
        if(num ==1)
        {
            Foto5();
            jTextArea1.setText("    \n" +
            "          Voce não quer arriscar sua miserável e pacata vida\n" +
            "     inútil por riquezas e glória. Para comemorar sua covardia\n" +
            "     nada melhor do que uma nova caneca cheia de cerveja!\n" +                    
            "     \n" +
            "     Este é o fim do jogo.");
            jTextField1.setText("     Aperte \"Aceitar\"para continuar");
            num = 100;
        }
        if(num ==2)
        {
            Foto6();
            jTextArea1.setText("    \n" +
            "          Voce acha melhor não desfocar da missão principal,\n" +
            "     afinal de contas você não é o sherif da cidade e não tem\n" +
            "     a mínima vontade de fazer o serviço de outra pessoa de\n" +                    
            "     graça!\n" +
            "     Você continua galopando com seu cavalo na estrada.");
            jTextField1.setText("     Aperte \"Aceitar\"para continuar");
            num = 3;
        }
        
        if(num ==6)
        {
            Foto15();
            jTextArea1.setText("    \n" +
            "          Você abraça o ovo de dragão com os dois braços e\n" +
            "     corre  desesperadamente  entre as  pedras, fugindo em\n" +
            "     \"zig-zag\" para evitar as baforadas de fogo!\n");
            jTextField1.setText("     Teste sua destreza, você deve tirar mais que 4.");
            destreza = 4;
            ataque = 20;
            inimigo = 4;
        }
    }//GEN-LAST:event_BtnRecusar1ActionPerformed

    private void UsarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsarActionPerformed
        
        if(pocao >0)
        {
            pocao = pocao -1;
            vida = vida + 60;
            jTextField3.setText(String.valueOf(vida));
            jTextField4.setText(String.valueOf(pocao));
            
            
            if(vida >100)
            {
                vida = 100;
                jTextField3.setText(String.valueOf(vida));
            }
        }
    }//GEN-LAST:event_UsarActionPerformed
    
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BntDestreza;
    private javax.swing.JButton BtnAceitar1;
    private javax.swing.JButton BtnRecusar1;
    private javax.swing.JButton Usar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
